apiVersion: v1
kind: Secret
metadata:
  name: drupal-mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root_password
  MYSQL_DATABASE: drupal-database
  MYSQL_USER: root

---
apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30095